[package]
name = "homie-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "homie"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
homie-agents.workspace = true
homie-client.workspace = true
homie-proto.workspace = true
homie-remote.workspace = true
homie-storage.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
homie-app = { path = "../homie-app" }
tempfile.workspace = true
