[package]
name = "homie-node"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "homie-node"
path = "src/main.rs"

[dependencies]
homie-client.workspace = true
homie-proto.workspace = true
homie-usage.workspace = true
getrandom.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
