//! Unpacking a verified update and swapping it in.
//!
//! A process cannot reliably delete the bundle it is executing out of, so the
//! swap runs from a detached `/bin/sh` helper that waits for homie to exit
//! first. The helper renames the old bundle aside before unpacking the new one
//! and puts it back if anything fails, so an interrupted install leaves a
//! working app rather than a hole where one used to be.

use std::fs;
use std::os::unix::process::CommandExt as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use crate::error::{Result, UpdateError};

/// Seconds the helper waits for homie to exit before giving up untouched.
const EXIT_GRACE_SECONDS: u32 = 60;

/// Expands the downloaded zip and returns the `.app` inside it.
pub fn unpack(archive: &Path, into: &Path) -> Result<PathBuf> {
    if into.exists() {
        fs::remove_dir_all(into)?;
    }
    fs::create_dir_all(into)?;
    // `ditto -x -k` is the counterpart of the `ditto -c -k` that built the
    // archive: unlike `unzip` it preserves the extended attributes and symlink
    // layout a signed bundle's seal depends on.
    let output = Command::new("/usr/bin/ditto")
        .arg("-x")
        .arg("-k")
        .arg(archive)
        .arg(into)
        .output()?;
    if !output.status.success() {
        return Err(UpdateError::tool(
            "ditto",
            String::from_utf8_lossy(&output.stderr).trim().to_owned(),
        ));
    }
    find_app(into)
}

fn find_app(directory: &Path) -> Result<PathBuf> {
    let mut apps = fs::read_dir(directory)?
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().is_some_and(|extension| extension == "app"))
        .collect::<Vec<_>>();
    match apps.len() {
        1 => Ok(apps.remove(0)),
        0 => Err(UpdateError::Integrity(
            "the update archive contains no .app bundle".to_owned(),
        )),
        count => Err(UpdateError::Integrity(format!(
            "the update archive contains {count} .app bundles"
        ))),
    }
}

/// Starts the swap helper and returns once it is running.
///
/// The caller must quit immediately afterwards: the helper is already polling
/// for this process to disappear.
pub fn launch_installer(staged_app: &Path, target: &Path, script_dir: &Path) -> Result<()> {
    fs::create_dir_all(script_dir)?;
    let script_path = script_dir.join("install.sh");
    let log_path = script_dir.join("install.log");
    fs::write(
        &script_path,
        installer_script(std::process::id(), staged_app, target),
    )?;

    let log = fs::File::create(&log_path)?;
    let errors = log.try_clone()?;
    Command::new("/bin/sh")
        .arg(&script_path)
        .stdin(Stdio::null())
        .stdout(log)
        .stderr(errors)
        // Its own process group, so the helper is not swept up in whatever
        // signals accompany homie's exit.
        .process_group(0)
        .spawn()?;
    Ok(())
}

/// The helper, as text. Pure so the ordering guarantees can be asserted in
/// tests and read without running an install.
pub fn installer_script(pid: u32, staged_app: &Path, target: &Path) -> String {
    let staged = shell_quote(&staged_app.to_string_lossy());
    let target = shell_quote(&target.to_string_lossy());
    let attempts = EXIT_GRACE_SECONDS * 10;
    format!(
        r#"#!/bin/sh
# Generated by homie's updater. Swaps the app bundle once homie has exited.
set -u

pid={pid}
staged={staged}
target={target}

waited=0
while kill -0 "$pid" 2>/dev/null; do
    waited=$((waited + 1))
    if [ "$waited" -gt {attempts} ]; then
        echo "homie (pid $pid) is still running after {EXIT_GRACE_SECONDS}s; not touching $target" >&2
        exit 1
    fi
    sleep 0.1
done

backup="$target.homie-previous"
rm -rf "$backup"
if [ -e "$target" ] && ! mv "$target" "$backup"; then
    echo "could not move $target aside; nothing was changed" >&2
    exit 1
fi

if /usr/bin/ditto "$staged" "$target"; then
    rm -rf "$backup"
    exec /usr/bin/open "$target"
fi

echo "install failed; restoring the previous bundle" >&2
rm -rf "$target"
if [ -e "$backup" ]; then
    mv "$backup" "$target"
fi
/usr/bin/open "$target"
exit 1
"#
    )
}

/// Wraps a path in single quotes for `/bin/sh`, which is the only escaping a
/// POSIX shell needs and the only one that is safe for arbitrary bytes.
fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn script() -> String {
        installer_script(
            4242,
            Path::new("/Users/giga/Library/Caches/homie/updates/0.2.0/homie.app"),
            Path::new("/Applications/homie.app"),
        )
    }

    #[test]
    fn waits_for_the_running_app_before_touching_anything() {
        let script = script();
        let wait = script.find("kill -0").expect("a wait loop");
        let mutate = script.find("mv \"$target\"").expect("the rename");
        assert!(wait < mutate, "the swap must come after the wait loop");
        assert!(script.contains("pid=4242"));
    }

    #[test]
    fn moves_the_old_bundle_aside_rather_than_deleting_it_first() {
        let script = script();
        let rename = script.find("mv \"$target\" \"$backup\"").expect("rename");
        let unpack = script.find("/usr/bin/ditto \"$staged\"").expect("ditto");
        assert!(rename < unpack);
        // The old bundle is only discarded once the new one is in place.
        let discard = script
            .find("rm -rf \"$backup\"\n    exec")
            .expect("cleanup");
        assert!(unpack < discard);
    }

    #[test]
    fn restores_the_previous_bundle_when_the_swap_fails() {
        let script = script();
        assert!(script.contains("mv \"$backup\" \"$target\""));
        assert!(script.contains("restoring the previous bundle"));
    }

    #[test]
    fn relaunches_the_app_on_both_paths() {
        assert_eq!(script().matches("/usr/bin/open \"$target\"").count(), 2);
    }

    #[test]
    fn quotes_paths_that_contain_spaces_and_quotes() {
        let script = installer_script(
            1,
            Path::new("/tmp/it's here/homie.app"),
            Path::new("/Applications/My Apps/homie.app"),
        );
        assert!(script.contains(r"staged='/tmp/it'\''s here/homie.app'"));
        assert!(script.contains("target='/Applications/My Apps/homie.app'"));
    }

    #[test]
    fn the_generated_script_is_valid_shell() {
        let output = Command::new("/bin/sh")
            .arg("-n")
            .arg("-c")
            .arg(script())
            .output()
            .expect("sh runs");
        assert!(
            output.status.success(),
            "sh -n rejected the script: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    /// Runs the real helper against throwaway bundles.
    ///
    /// Only the relaunch is stubbed out — a test must not hand a bundle to
    /// LaunchServices — so the wait, rename, unpack, and restore paths are the
    /// shipped ones. `pid` is a process that has already exited, which makes
    /// the wait loop fall through immediately.
    fn run_installer(staged: &Path, target: &Path, pid: u32) -> std::process::Output {
        let script =
            installer_script(pid, staged, target).replace("/usr/bin/open", "echo relaunched");
        Command::new("/bin/sh")
            .arg("-c")
            .arg(script)
            .output()
            .expect("sh runs")
    }

    /// A pid that is guaranteed not to be running: spawn something trivial and
    /// reap it.
    fn dead_pid() -> u32 {
        let mut child = Command::new("/usr/bin/true").spawn().expect("spawn");
        let pid = child.id();
        child.wait().expect("reap");
        pid
    }

    fn fake_bundle(root: &Path, name: &str, marker: &str) -> PathBuf {
        let bundle = root.join(name);
        fs::create_dir_all(bundle.join("Contents/MacOS")).expect("layout");
        fs::write(bundle.join("Contents/MacOS/homie"), marker).expect("binary");
        bundle
    }

    #[test]
    fn the_helper_actually_replaces_the_bundle() {
        let directory = tempfile::tempdir().expect("temp dir");
        let staged = fake_bundle(directory.path(), "staged.app", "new");
        let target = fake_bundle(directory.path(), "homie.app", "old");

        let output = run_installer(&staged, &target, dead_pid());
        assert!(
            output.status.success(),
            "installer failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(
            fs::read_to_string(target.join("Contents/MacOS/homie")).expect("read"),
            "new"
        );
        assert!(
            !directory.path().join("homie.app.homie-previous").exists(),
            "the backup is discarded once the swap succeeds"
        );
        assert!(String::from_utf8_lossy(&output.stdout).contains("relaunched"));
    }

    #[test]
    fn the_helper_restores_the_old_bundle_when_the_unpack_fails() {
        let directory = tempfile::tempdir().expect("temp dir");
        let target = fake_bundle(directory.path(), "homie.app", "old");
        // A staged path that does not exist is exactly what a half-cleaned
        // cache directory looks like, and ditto fails on it.
        let missing = directory.path().join("staged.app");

        let output = run_installer(&missing, &target, dead_pid());
        assert!(
            !output.status.success(),
            "a failed unpack must report failure"
        );
        assert!(target.exists(), "the app must still be there");
        assert_eq!(
            fs::read_to_string(target.join("Contents/MacOS/homie")).expect("read"),
            "old",
            "the original bundle must be restored byte for byte"
        );
        assert!(!directory.path().join("homie.app.homie-previous").exists());
    }

    #[test]
    fn the_helper_leaves_the_app_alone_when_the_process_never_exits() {
        let directory = tempfile::tempdir().expect("temp dir");
        let staged = fake_bundle(directory.path(), "staged.app", "new");
        let target = fake_bundle(directory.path(), "homie.app", "old");

        let mut hung = Command::new("/bin/sleep").arg("30").spawn().expect("spawn");
        // Shorten the wait loop rather than blocking the suite for 60s.
        let script = installer_script(hung.id(), &staged, &target)
            .replace("/usr/bin/open", "echo relaunched")
            .replace("-gt 600", "-gt 3");
        let output = Command::new("/bin/sh")
            .arg("-c")
            .arg(script)
            .output()
            .expect("sh runs");
        let _ = hung.kill();
        let _ = hung.wait();

        assert!(!output.status.success());
        assert_eq!(
            fs::read_to_string(target.join("Contents/MacOS/homie")).expect("read"),
            "old",
            "a still-running homie must never have its bundle swapped"
        );
    }

    #[test]
    fn unpacking_finds_the_single_app_in_an_archive() {
        let directory = tempfile::tempdir().expect("temp dir");
        let source = directory.path().join("source");
        fs::create_dir_all(source.join("homie.app/Contents/MacOS")).expect("bundle layout");
        fs::write(source.join("homie.app/Contents/MacOS/homie"), b"binary").expect("binary");

        let archive = directory.path().join("homie.zip");
        let status = Command::new("/usr/bin/ditto")
            .arg("-c")
            .arg("-k")
            .arg("--keepParent")
            .arg(source.join("homie.app"))
            .arg(&archive)
            .status()
            .expect("ditto runs");
        assert!(status.success());

        let unpacked = unpack(&archive, &directory.path().join("staged")).expect("unpack");
        assert_eq!(unpacked.file_name().unwrap(), "homie.app");
        assert!(unpacked.join("Contents/MacOS/homie").exists());
    }

    #[test]
    fn an_archive_without_a_bundle_is_rejected() {
        let directory = tempfile::tempdir().expect("temp dir");
        let loose = directory.path().join("loose");
        fs::create_dir_all(&loose).expect("dir");
        fs::write(loose.join("README.txt"), b"not an app").expect("file");

        let archive = directory.path().join("loose.zip");
        let status = Command::new("/usr/bin/ditto")
            .arg("-c")
            .arg("-k")
            .arg(&loose)
            .arg(&archive)
            .status()
            .expect("ditto runs");
        assert!(status.success());

        let error = unpack(&archive, &directory.path().join("staged"))
            .expect_err("a bundle-less archive must be refused");
        assert!(matches!(error, UpdateError::Integrity(_)));
    }
}
